### ISSUE TITLE
error Lyrics can't be romaji

### ISSUE THREAD

**Issue by pinglingalvin** [41pha1/spicetify-extensions#11]
Hi, I'm using your ekstension to install an spotify romaji and romaja ekstension for the Spiteify but, it doesn't work at all and i try to CTRL + Tab and it didn't change at all it still kanji words and doesn't show romaji lyrics and i installed with your file in github and the result is same, it doesn't change, can you help me bro with the issues?

-AP

**Comment by Yokai-dev** [comment]
I got the same problem. Would be much appreaciated if we got any updates on this.

**Comment by 41pha1** [comment]
Maybe this issue regarding getting this to work for lyrics plus might be helpful for you?
https://github.com/41pha1/spicetify-extensions/issues/8

Otherwise its not easy for me to help you without knowing what is causing the problem, as it seems to work for most people so far... Maybe take a look at the output of the dev console, that can be enabled with `spicetify enable-devtools ` and then pressing ctrl + shift + i.

**Comment by Yokai-dev** [comment]
The issue you mentioned helped me out a lot. Now everything works fine.

Thanks a lot :)

**Comment by vathanac** [comment]
> 



> Maybe this issue regarding getting this to work for lyrics plus might be helpful for you? #8
> 
> Otherwise its not easy for me to help you without knowing what is causing the problem, as it seems to work for most people so far... Maybe take a look at the output of the dev console, that can be enabled with `spicetify enable-devtools ` and then pressing ctrl + shift + i.
> 
> Are there any errors regarding this extension, that show up there?

I got it working with [lyric plus](https://i.imgur.com/RyHn5Xk.png) but not [spotify lyric](https://i.imgur.com/mhfpLw1.png).

**Comment by Arghadatta** [comment]
> Maybe this issue regarding getting this to work for lyrics plus might be helpful for you? #8
> 
> Otherwise its not easy for me to help you without knowing what is causing the problem, as it seems to work for most people so far... Maybe take a look at the output of the dev console, that can be enabled with `spicetify enable-devtools ` and then pressing ctrl + shift + i.
> 
> Are there any errors regarding this extension, that show up there?

i throughly checked through the script and after testing ,found that it now works in spotify 1.1.97.962 version and downwards but breaks down after that,devtool console don't give any info at all but the script don't run.
its all i can say now.

**Comment by albertoo1275** [comment]
Still doesn't work. I'd love to cope with lyric-plus but it seems that I can't manage to do that
![image](https://user-images.githubusercontent.com/120394258/207071127-e78f2c8a-b0dc-453d-8550-8a32f89af3c3.png)
![image](https://user-images.githubusercontent.com/120394258/207071167-fdb6d039-bb3e-4402-bb9d-239388152827.png)

**Comment by Yokai-dev** [comment]
Overwrite the files in your \AppData\Local\spicetify\CustomApps\lyrics-plus folder with the files here: https://github.com/41pha1/spicetify-cli/tree/lyrics-converter/CustomApps/lyrics-plus

You can download these files if you go to the main directory and just download the project as a zip and navigate to the lyrics-plus folder. Then copy them and replace them in your Local folder.

This worked for me, since it didn't work for me at first as well. But by doing this you can see the translation button.

If you're facing any issues, just ask :)

**Comment by pinglingalvin** [comment]
![Screenshot (286)](https://user-images.githubusercontent.com/120280602/207208881-1824ef03-c066-4681-bf78-74f251f9fe20.png)
![Screenshot (287)](https://user-images.githubusercontent.com/120280602/207209100-b070e31a-5de2-4dfb-a182-05df00558c86.png)


> Overwrite the files in your \AppData\Local\spicetify\CustomApps\lyrics-plus folder with the files here: https://github.com/41pha1/spicetify-cli/tree/lyrics-converter/CustomApps/lyrics-plus
> 
> You can download these files if you go to the main directory and just download the project as a zip and navigate to the lyrics-plus folder. Then copy them and replace them in your Local folder.
> 
> This worked for me, since it didn't work for me at first as well. But by doing this you can see the translation button.
> 
> If you're facing any issues, just ask :)



Hi, im using your methods to fix it and it still can't be worked and i tried to reinstall the spotify and spicetify and it worst it can't use for karaoke now  can you help me to fix it!

- AP

**Comment by 41pha1** [comment]
I am sorry that so many people are experiencing issues right now and are unable to do karaoke anymore.

I would love to investigate further and make this extension work for everyone again as well as implement some of the requested features.

Unfortunately I have to prepare for my finals right now and am really short on time

**Comment by pinglingalvin** [comment]
> 

Ouhh sorry to take your time, but now the romaji can be translated and have the button but for the romaja version for the korean song and the karaoke system for spicetify aren't available and still error, i hope you can fix it ASAP, Just take your time man.
P.S Good Luck bro for your exam 

- AP

> I am sorry that so many people are experiencing issues right now and are unable to do karaoke anymore.
> 
> I would love to investigate further and make this extension work for everyone again as well as implement some of the requested features.
> 
> Unfortunately I have to prepare for my finals right now and am really short on time

**Comment by Yokai-dev** [comment]
Yeah the karaoke button is also not available for me, but I only tested with romaji, since I don't really listen to korean music. But if romaji works then that's all good. I'm going to look into romaja for you as well, maybe I can find something that helps.

I'll keep you updated :)

**Comment by Yokai-dev** [comment]
@pinglingalvin Okay, so I took a look at the code yesterday evening, but I can't find any code about Romaja, only Romaji, so lyrics-plus is not for Korean lyrics yet I think. Maybe it is, but they forgot to add it. I don't have a lot of knowledge about the code, so I can't really help writing some code to let Romaja work. Anyways, now you know why there's no Romaja.

There are 2 extensions on the marketplace in Spicetify for Romaja and Romaji, but they don't work for most people atm, so I guess we just gotta wait patiently and give the guy some time.

**Comment by pinglingalvin** [comment]
> @pinglingalvin Okay, so I took a look at the code yesterday evening, but I can't find any code about Romaja, only Romaji, so lyrics-plus is not for Korean lyrics yet I think. Maybe it is, but they forgot to add it. I don't have a lot of knowledge about the code, so I can't really help writing some code to let Romaja work. Anyways, now you know why there's no Romaja.
> 
> There are 2 extensions on the marketplace in Spicetify for Romaja and Romaji, but they don't work for most people atm, so I guess we just gotta wait patiently and give the guy some time.

Ouhh okay, so in the marketplace i can't translate korean song to romaja so any solution because the romaja lyrics only work at Spotify lyrics, so then I press the CTRL + Tab it's still doesn't work. so for the romaja i think is for Spotify Application not for Lyric plus

My bad, my english bad
- AP

**Comment by Yokai-dev** [comment]
You're correct.

Don't worry about your English, it's good enough to understand.

**Comment by 41pha1** [comment]
Sorry for the long wait you all and thank you for being patient, I have added a hotfix that seems to solve the issues for all the devices I had time testing it on.

When loading the extensions from marketplace it can take up to day for the old file to be cleared from the jsdeliver cache.

I hope this solves it for you guys, and I definitely plan to continue working on these extensions when my schedule clears up a little! 

(For example adding romaja to lyrics plus, some sort of dual viewing mode better UI and so on...)

**Comment by 41pha1** [comment]
@Yokai-dev 
Thank you for managing my issues while I was away! <3

**Comment by 41pha1** [comment]
> Still doesn't work. I'd love to cope with lyric-plus but it seems that I can't manage to do that

Thats weird it should be working with lyrics-plus at least with romaji for now, the code is complete different so the update that broke these extensions did not effect the lyrics-plus fork

**Comment by rahaaatul** [comment]
Same for me, I tried the mentioned #8 method but doesn't work.


https://user-images.githubusercontent.com/86149861/208220840-b0551d76-ac2f-4b12-8927-7cb0fc301814.mp4

Spotify for Windows
1.2.0.1165.gabf054ab
Spicetify v2.14.3
Theme: Fluent / light
Extensions: fluent.js, adblock.js, fullAppDisplayMod.js, romaja_lyrics.js, romaji_lyrics.js
Custom apps: marketplace

**Comment by 41pha1** [comment]
@rahaaatul Thanks for the detailed description of your problem!
The fix for this extensions should be applied as soon as the CDN updates its cache, which is up to a day from now.
That it is not working with lyrics plus for you with lyrics plus seems a bit strange, i just tested it on a fresh device with and testet for compatibility with the extensions you described and seemed to be working fine.

https://github.com/41pha1/spicetify-cli/tree/lyrics-converter/CustomApps/lyrics-plus

Have you downloaded the files from the correct branch?

Are the additional files like translator.js in the  \AppData\Local\spicetify\CustomApps\lyrics-plus directory?

**Comment by rahaaatul** [comment]
> @rahaaatul Thanks for the detailed description of your problem! The fix for this extensions should be applied as soon as the CDN updates its cache, which is up to a day from now. That it is not working with lyrics plus for you with lyrics plus seems a bit strange, i just tested it on a fresh device with and testet for compatibility with the extensions you described and seemed to be working fine.
> 
> https://github.com/41pha1/spicetify-cli/tree/lyrics-converter/CustomApps/lyrics-plus
> 
> Have you downloaded the files from the correct branch?
> 
> Are the additional files like translator.js in the \AppData\Local\spicetify\CustomApps\lyrics-plus directory?

It's in there, It's working fine now after I downgraded to 1.2.0.1165.

**Comment by Yokai-dev** [comment]
> @Yokai-dev Thank you for managing my issues while I was away! <3

No problem, always happy to help :)

**Comment by kdelia12** [comment]
> 

yes, but it not showing the translate button

**Comment by Yokai-dev** [comment]
> 

For most people it's working and showing. Have you installed spotify via browser? Have you tried reinstalling and doing the steps mentioned above again? That's all the help I can offer so far. Just try that and then see if it'll work.
