### ISSUE TITLE
Romaji extension not working

### ISSUE THREAD

**Issue by EliasRonefors** [41pha1/spicetify-extensions#15]
Japanese text is not romanized on any song. Pressing ctrl+tab doesn't change anything. I looked in other issues threads but could not find a way to solve the problem.

![image](https://user-images.githubusercontent.com/90244703/235159197-9d34a5ce-280c-4b8e-8da8-8f967a788f04.png)

Spotify for Windows
1.1.85.895.g2a71e1b8
Spicetify v2.17.2
Theme: marketplace / dracula
Extensions: webnowplaying.js, adblock.js, hidePodcasts.js, romaji_lyrics.js, playlist-icons.js
Custom apps: marketplace

**Comment by Gerges4949** [comment]
Did you find any solution ?
having the same problem

**Comment by antonio-gil** [comment]
Hi @EliasRonefors and @Gerges4949 

I have recently found a possible workaround for this issue (assuming that is the same, of course), and it has been documented on issue #17 .
