### ISSUE TITLE
Romaji extension not working 

### ISSUE THREAD

**Issue by Gerges4949** [41pha1/spicetify-extensions#16]
I have downloaded the extension throw the marketplace but didn't work  I have also tried to do download and add the "romaji_lyrics" manually but didn't work
although  the romaja extension work normally
anyone phasing the same problem or know how to solve it ?

**Comment by antonio-gil** [comment]
Hi!

I have recently found a potential workaround for this issue (assuming that is the same, of course), and it has been documented on issue #17.
