### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by zak0chana** [41pha1/spicetify-extensions#18]
![image](https://github.com/41pha1/spicetify-extensions/assets/122036843/4b214b15-cde4-4eb6-b501-8370c0ef9f24)

song = "しかばねの踊り" by Kikuo
sign = "憑"

**Comment by Gerges4949** [comment]
can you send the java script file ? and which spicetify version are you using ? because I use v2.22.2 but the extension doesn't work for me

**Comment by zak0chana** [comment]
I downloaded from the marketplace so idk the version and I don't think I can send the js file

**Comment by Gerges4949** [comment]
just to make sure you just press ctrl + tab and it convert the lyrics ? 
I have both extensions for Japanese and Korean but for some reason it works for Korean only

**Comment by zak0chana** [comment]
still

**Comment by antonio-gil** [comment]
> just to make sure you just press ctrl + tab and it convert the lyrics ? I have both extensions for Japanese and Korean but for some reason it works for Korean only

I was having a very similar today with current extension version (i.e. the one available in this repository), and found a [potential workaround](https://github.com/41pha1/spicetify-extensions/issues/17#issuecomment-1756437855) which I documented on issue #17.

Can't say for sure if that will help you, but I think that it'll worth a shot.

Regards.

**Comment by Gerges4949** [comment]
> > just to make sure you just press ctrl + tab and it convert the lyrics ? I have both extensions for Japanese and Korean but for some reason it works for Korean only
> 
> I was having a very similar today with current extension version (i.e. the one available in this repository), and found a [potential workaround](https://github.com/41pha1/spicetify-extensions/issues/17#issuecomment-1756437855) which I documented on issue #17.
> 
> Can't say for sure if that will help you, but I think that it'll worth a shot.
> 
> Regards.
you are a life savior 
thank you so much 
tried it and worked

**Comment by antonio-gil** [comment]
@Gerges4949 : awesome! Glad that the workaround worked for you too!
