### ISSUE TITLE
Japanese Romaji Lyrics translator glich 

### ISSUE THREAD

**Issue by Qmalamos1** [41pha1/spicetify-extensions#20]
On the lyrics page, there is a glichy div that made his way into the lyrics. 
![Captura de pantalla 2023-10-12 194026](https://github.com/41pha1/spicetify-extensions/assets/116726635/88007b7c-478a-4c95-bd4d-53fba2510257)
![image](https://github.com/41pha1/spicetify-extensions/assets/116726635/d0969faf-0dd9-44a6-9844-7bb93253328f)

**Comment by alvinolubis** [comment]
have you found a solve for this issue? it just occurred to me today
