### ISSUE TITLE
Romaja.js not working

### ISSUE THREAD

**Issue by dioodle** [41pha1/spicetify-extensions#24]
I tried installing it through spicetify and manually, both of those methods didnt work. I even tried spicetify restore and then reapplying it, stil didnt work, and closing the program, and even change to a different kpop song. All didn;t work, can you help me fix it? I really wanna karaoke korean songs. Thanks :pray:

**Comment by mattc28** [comment]
Likewise, tried with both japanese and korean songs (with both romaja and romaji) and not found it to work

**Comment by CharlieVibin** [comment]
it isnt just this extension its the whole of spotify romanized plugins in general probably becuase of the new update instead i recommend using this little lyrics thing for now 
![image](https://github.com/41pha1/spicetify-extensions/assets/114245189/3026884a-bfa4-4f75-9fa4-424af0d421d7)

**Comment by mattc28** [comment]
> it isnt just this extension its the whole of spotify romanized plugins in general probably becuase of the new update instead i recommend using this little lyrics thing for now ![image](https://private-user-images.githubusercontent.com/114245189/329811802-3026884a-bfa4-4f75-9fa4-424af0d421d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTg5NjQsIm5iZiI6MTcxNTUxODY2NCwicGF0aCI6Ii8xMTQyNDUxODkvMzI5ODExODAyLTMwMjY4ODRhLWJmYTQtNGY3NS05ZmE0LTQyNGFmMGQ0MjFkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMjU3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjZjY2IyMjczNTg0OTc4ZDcwM2JlZThiOGY4YTQzOGRlYTMxNjczOTRlOTQ4YTkyMTMwNGM3NWZhMmI3ODZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fM-zy7hGC8Mwnpo3PpWQDmN0iYqbrksMIBDb4CHeknk)

What plugin is that?

**Comment by 41pha1** [comment]
That plugin is the custom app lyrics-plus, which also contains the romaji / romaja converter from this repo and is still being maintained by the spicetify community.

You can install it by running:
```
spicetify config custom_apps lyrics_plus
spicetify apply
```

I also suggest using it until I get to maintaining this repo again.

**Comment by hihit111** [comment]
when I do that it says something went wrong try reloading the page

**Comment by yatsukiko** [comment]
I updated it, might break per update, if it does then I will spend more time on it to make it more flexible but for now it works: 
https://github.com/yatsukiko/spicetify-extensions

**Comment by hihit111** [comment]
alr
