### ISSUE TITLE
Hangul to Romaji Support

### ISSUE THREAD

**Issue by surya27895** [41pha1/spicetify-extensions#4]
thanks for your great work with the marketplace ext. and the awesome lyrics-plus fork!!
I hope you can add support with hangul too, since i see few project around github about it and maybe can integrated with your project.

best regards.

**Comment by 41pha1** [comment]
This is an amazing suggestion!
I will try to implement this into lyrics plus as well as this extension when I have some spare time again. 
Plus fixing up the UI experience and reliability of this hacked together extension...

**Comment by 41pha1** [comment]
I added a Hangul lyric conversion extension as well now, I hope it works for you!

**Comment by surya27895** [comment]
it's works perfectly.
thanks for your amazing works
hope it also implemented to lyrics-plus soon!

**Comment by 41pha1** [comment]
I will probably open a new pull request once I get it done :D
