### ISSUE TITLE
Suggestions: make Japanese and romaji show at the same time

### ISSUE THREAD

**Issue by catalpaaa** [41pha1/spicetify-extensions#7]
Example:
空飛ぶ羽根と引き換えに 繋ぎ合う手を選んだ
sora tobu hane to hikikae ni tsunagiau te o eranda

それでも空に魅せられて 夢を重ねるのは罪か
soredemo sora ni miserarete yume o kasaneru no wa tsumi ka

**Comment by Arghadatta** [comment]
either in dual pane;l but sentence by sentence will be very odd

**Comment by jang-geon** [comment]
I need too

**Comment by Yokai-dev** [comment]
> either in dual pane;l but sentence by sentence will be very odd

I honestly think the example would be cleaner then the dual panels. Then it wouldn't feel cramped.
