### ISSUE TITLE
Not Working with Lyrics-Plus for me

### ISSUE THREAD

**Issue by karimawii** [41pha1/spicetify-extensions#8]
Both the marketplace version and using the JavaScript file and adding it to config have the same issue

![Spotify_ujnUJXYkx1](https://user-images.githubusercontent.com/69881381/201769362-73426cf6-ea28-439c-b97b-d8ae8badf02e.gif)

**Comment by 41pha1** [comment]
The extension sadly only works for the Spotify Lyrics, but if you go to me GitHub there is a fork of the spicetify-cli which contains a modified version of lyrics plus, if you replace your lyrics plus folder with that version it should work for lyrics plus as well, hope this works for you!

**Comment by ItsPinkLasagna** [comment]
> 
I am having some trouble doing this and finding the fork, How do I do this?

**Comment by 41pha1** [comment]
The fork should be linked on the readme of this extension. Or here: https://github.com/41pha1/spicetify-cli/tree/lyrics-converter/CustomApps/lyrics-plus, hope this helps!

**Comment by ItsPinkLasagna** [comment]
Ahh I did found the right fork,thanks! but this might be a stupid question but how do I Install it? What do I put in the Extension folder?

**Comment by 41pha1** [comment]
If you are on windows you can replace the files in ...\AppData\Local\spicetify\CustomApps\lyrics-plus with the ones from this fork and after that you apply the changes with `spicetify apply`

**Comment by ItsPinkLasagna** [comment]
Oh my god, that did it!
Thank you so much! Helped me a lot
